USE EIRA;
GO
DROP TABLE IF EXISTS APP_CONFIGURATION_LOAD_INFORMATION;
GO
DROP TABLE IF EXISTS APP_CONFIGURATION_FOLLOW_UP_REPORT;
GO
DROP TABLE IF EXISTS APP_CONFIGURATION_GLOBAL_REPORT;
GO
DROP TABLE IF EXISTS APP_CONFIGURATION_ISSUE_TYPE;
GO
DROP TABLE IF EXISTS BAS_PROJECT;
GO
DROP TABLE IF EXISTS BAS_FIELD;
GO
DROP TABLE IF EXISTS BAS_ISSUE_TYPE;
GO